export default {
  translations: {
    'A_Modifier': 'V 的{word}',
    'Direct-Object_of': 'V {word}',
    'Indirect-Object_of': 'V（到）{word}',
    'Measure': '一……{word}',
    'Modifier': 'ADV {word}',
    'Modifies': '{word}（的）N',
    'N_Modifier': 'N {word}',
    'Object': '{word} OBJECT',
    'Object_of': 'V（为）{word}',
    'Possession': '{word}之 N',
    'Possessor': 'N 之{word}',
    'Subject_of': '{word} V',
    'and/or': '{word}、N',
    'PP_与': '与 N {word}',
    'PP_为': '为 N {word}',
    'PP_以': '以 N {word}',
    'PP_向': '向 N {word}',
    'PP_在': '在 N {word}',
    'PP_如': '如 N {word}',
    'PP_将': '将 N {word}',
    'PP_把': '把 N {word}',
    'PP_对': '对 N {word}',
    'PP_因': '因 N {word}',
    'PP_给': '给 N {word}',
    'PP_就': '就 N {word}',
    'SentObject_of': 'N {word}',
    'SentObject': '{word} CLAUSE',
    'Subject': 'N {word}',
    'Direct-Object': '{word} COMPLEMENT',
    'Direct-SentObject': '……{word}……',
    'Indirect-Object': '{word} N',
    'PP_于': '……{word}于……',
    'Enter a search term in {l2}...': 'Enter a search term in {l2}...',
    'Contact {l2} Zero to Hero': 'Contact {l2} Zero to Hero',
    'For the love of {l2} words.': 'For the love of {l2} words.',
    'Search the entire YouTube for {l2} videos with CC': 'Search the entire YouTube for {l2} videos with CC',
    'Study any YouTube video that has {l2} subtitles.': 'Study any YouTube video that has {l2} subtitles.',
    'Courses that take your {l2} to the next level.': 'Courses that take your {l2} to the next level.',
    'Paste {l1} translation here': 'Paste {l1} translation here',
    'Paste {l2} text here': 'Paste {l2} text here',
    'This is where you can enjoy reading a variety of {l2} books with the help of hover dictionary and the ability to save words.': 'This is where you can enjoy reading a variety of {l2} books with the help of hover dictionary and the ability to save words.',
    copyPasteCSV: '<b>Copy</b> the text below and <b>paste</b> into your spreadsheet program, or a flashcard app like Anki or Quizlet.',
    textReaderIntro: 'Write or paste in some {l2} text, and annotated text will show up below the textbox. You can also use <b>Markdown or HTML tags</b>. Everything is autosaved to your browser’s <code>localStorage</code>, so even if you refresh your browser everything you entered is still here.',
    libraryIntro: 'Read books from various {l2} sources directly in our Library.',
    'Images of “{text}” on the Web': 'Images of “{text}” on the Web',
    'Collocations with “{ text }”': 'Collocations with “{ text }”',
    'Collocations with “{text}”': 'Collocations with “{text}”',
    'Sentences with “{text}”': 'Sentences with “{text}”',
    '“{text}” videos on YouTube': '“{text}” videos on YouTube',
    'Collocations provided by': 'Collocations provided by',
    'Sentences provided by': 'Sentences provided by',
    'Search for more sentences at': 'Search for more sentences at',
    '"{word}" and/or ...': '"{word}" and/or ...',
    'nouns modified by "{word}"': 'nouns modified by "{word}"',
    'objects of "{word}"': 'Objects of "{word}"',
    'subjects of "{word}"': '"Subjects of "{word}',
    'prepositional phrases': '介词短语',
    'pronominal objects of "{word}"': 'Pronominal objects of "{word}"',
    'verbs with "{word}" as object': 'Verbs with "{word}" as object',
    'verbs with "{word}" as subject': 'Verbs with "{word}" as subject',
    'adjective predicates of "{word}"': 'Adjective predicates of "{word}"',
    '"{word}" is a ...': '"{word}" is a ...',
    '{word}\'s ...': '{word}\'s ...',
    'possessors of "{word}"': 'Possessors of "{word}"',
    'pronominal possessors of "{word}"': 'Pronominal possessors of "{word}"',
    'usage patterns': 'Usage patterns',
    '... is a "{word}"': '... is a "{word}"',
    'verbs with particle "up" and "{word}" as object': 'Verbs with particle "up" and "{word}" as object',
    'verbs with particle "out" and "{word}" as object': 'Verbs with particle "out" and "{word}" as object',
    'verbs with particle "down" and "{word}" as object': 'Verbs with particle "down" and "{word}" as object',
    'verbs with particle "off" and "{word}" as object': 'Verbs with particle "off" and "{word}" as object',
    'verbs with particle "over" and "{word}" as object': 'Verbs with particle "over" and "{word}" as object',
    'modifiers of "{word}"': 'Modifiers of "{word}"',
    'infinitive objects of "{word}"': 'Infinitive objects of "{word}"',
    'verbs complemented by "{word}"': 'Verbs complemented by "{word}"',
    'verbs before "{word}"': 'Verbs before "{word}"',
    'subjects of "be {word}"': 'Subjects of "be {word}"',
    'verbs with particle "away" and "{word}" as object': 'Verbs with particle "away" and "{word}" as object',
    'Show {count} More': 'Show {count} More',
    '-ing objects of "{word}"': '-ing objects of "{word}"',
    'adjectives after "{word}"': 'adjectives after "{word}"',
    'adjectives modified by "{word}"': 'adjectives modified by "{word}"',
    'adverbs modified by "{word}"': 'adverbs modified by "{word}"',
    'as reflexive': 'as reflexive',
    'complements of "{word}"': 'complements of "{word}"',
    'in passive': 'in passive',
    'it\'s "{word}" to ...': 'it\'s "{word}" to ...',
    'objects of "{word} across"': 'objects of "{word} across"',
    'objects of "{word} along"': 'objects of "{word} along"',
    'objects of "{word} apart"': 'objects of "{word} apart"',
    'objects of "{word} around"': 'objects of "{word} around"',
    'objects of "{word} aside"': 'objects of "{word} aside"',
    'objects of "{word} away"': 'objects of "{word} away"',
    'objects of "{word} down"': 'objects of "{word} down"',
    'objects of "{word} in"': 'objects of "{word} in"',
    'objects of "{word} off"': 'objects of "{word} off"',
    'objects of "{word} on"': 'objects of "{word} on"',
    'objects of "{word} open"': 'objects of "{word} open"',
    'objects of "{word} out"': 'objects of "{word} out"',
    'objects of "{word} over"': 'objects of "{word} over"',
    'objects of "{word} through"': 'objects of "{word} through"',
    'objects of "{word} unto"': 'objects of "{word} unto"',
    'objects of "{word} up"': 'objects of "{word} up"',
    'objects of "{word} upon"': 'objects of "{word} upon"',
    'objects of "{word} whole"': 'objects of "{word} whole"',
    'particles after "{word}"': 'particles after "{word}"',
    'particles after "{word}" with object': 'particles after "{word}" with object',
    'pronominal subjects of "{word}"': 'pronominal subjects of "{word}"',
    'verbs modified by "{word}"': 'verbs modified by "{word}"',
    'verbs with particle "across" and "{word}" as object': 'verbs with particle "across" and "{word}" as object',
    'verbs with particle "along" and "{word}" as object': 'verbs with particle "along" and "{word}" as object',
    'verbs with particle "apart" and "{word}" as object': 'verbs with particle "apart" and "{word}" as object',
    'verbs with particle "around" and "{word}" as object': 'verbs with particle "around" and "{word}" as object',
    'verbs with particle "aside" and "{word}" as object': 'verbs with particle "aside" and "{word}" as object',
    'verbs with particle "in" and "{word}" as object': 'verbs with particle "in" and "{word}" as object',
    'verbs with particle "on" and "{word}" as object': 'verbs with particle "on" and "{word}" as object',
    'verbs with particle "open" and "{word}" as object': 'verbs with particle "open" and "{word}" as object',
    'verbs with particle "through" and "{word}" as object': 'verbs with particle "through" and "{word}" as object',
    'verbs with particle "unto" and "{word}" as object': 'verbs with particle "unto" and "{word}" as object',
    'verbs with particle "upon" and "{word}" as object': 'verbs with particle "upon" and "{word}" as object',
    'verbs with particle "whole" and "{word}" as object': 'verbs with particle "whole" and "{word}" as object',
    'wh-words following "{word}"': 'wh-words following "{word}"',
    '"{word}" as ...': '"{word}" as ...',
    '... as "{word}"': '... as "{word}"',
    '"{word}" in ...': '"{word}" in ...',
    '... in "{word}"': '... in "{word}"',
    '"{word}" of ...': '"{word}" of ...',
    '... of "{word}"': '... of "{word}"',
    '"{word}" at ...': '"{word}" at ...',
    '... at "{word}"': '... at "{word}"',
    '"{word}" for ...': '"{word}" for ...',
    '... for "{word}"': '... for "{word}"',
    '"{word}" on ...': '"{word}" on ...',
    '... on "{word}"': '... on "{word}"',
    '"{word}" to ...': '"{word}" to ...',
    '... to "{word}"': '... to "{word}"',
    '"{word}" by ...': '"{word}" by ...',
    '... by "{word}"': '... by "{word}"',
    '"{word}" with ...': '"{word}" with ...',
    '... with "{word}"': '... with "{word}"',
    '"{word}" from ...': '"{word}" from ...',
    '... from "{word}"': '... from "{word}"',
    '"{word}" about ...': '"{word}" about ...',
    '... about "{word}"': '... about "{word}"',
    '"{word}" into ...': '"{word}" into ...',
    '... into "{word}"': '... into "{word}"',
    '"{word}" over ...': '"{word}" over ...',
    '... over "{word}"': '... over "{word}"',
    '"{word}" despite ...': '"{word}" despite ...',
    '... despite "{word}"': '... despite "{word}"',
    '"{word}" after ...': '"{word}" after ...',
    '... after "{word}"': '... after "{word}"',
    '"{word}" before ...': '"{word}" before ...',
    '... before "{word}"': '... before "{word}"',
    '"{word}" within ...': '"{word}" within ...',
    '... within "{word}"': '... within "{word}"',
    '"{word}" while ...': '"{word}" while ...',
    '... while "{word}"': '... while "{word}"',
    '"{word}" under ...': '"{word}" under ...',
    '... under "{word}"': '... under "{word}"',
    '"{word}" if ...': '"{word}" if ...',
    '... if "{word}"': '... if "{word}"',
    '"{word}" through ...': '"{word}" through ...',
    '... through "{word}"': '... through "{word}"',
    '"{word}" whether ...': '"{word}" whether ...',
    '... whether "{word}"': '... whether "{word}"',
    '"{word}" via ...': '"{word}" via ...',
    '... via "{word}"': '... via "{word}"',
    '"{word}" past ...': '"{word}" past ...',
    '... past "{word}"': '... past "{word}"',
    '"{word}" during ...': '"{word}" during ...',
    '... during "{word}"': '... during "{word}"',
    '"{word}" like ...': '"{word}" like ...',
    '... like "{word}"': '... like "{word}"',
    '"{word}" against ...': '"{word}" against ...',
    '... against "{word}"': '... against "{word}"',
    '"{word}" towards ...': '"{word}" towards ...',
    '... towards "{word}"': '... towards "{word}"',
    '"{word}" down ...': '"{word}" down ...',
    '... down "{word}"': '... down "{word}"',
    '"{word}" because ...': '"{word}" because ...',
    '... because "{word}"': '... because "{word}"',
    '"{word}" off ...': '"{word}" off ...',
    '... off "{word}"': '... off "{word}"',
    '"{word}" until ...': '"{word}" until ...',
    '... until "{word}"': '... until "{word}"',
    '"{word}" along ...': '"{word}" along ...',
    '... along "{word}"': '... along "{word}"',
    '"{word}" alongside ...': '"{word}" alongside ...',
    '... alongside "{word}"': '... alongside "{word}"',
    '"{word}" out ...': '"{word}" out ...',
    '... out "{word}"': '... out "{word}"',
    '"{word}" than ...': '"{word}" than ...',
    '... than "{word}"': '... than "{word}"',
    '"{word}" near ...': '"{word}" near ...',
    '... near "{word}"': '... near "{word}"',
    '"{word}" throughout ...': '"{word}" throughout ...',
    '... throughout "{word}"': '... throughout "{word}"',
    '"{word}" per ...': '"{word}" per ...',
    '... per "{word}"': '... per "{word}"',
    '"{word}" between ...': '"{word}" between ...',
    '... between "{word}"': '... between "{word}"',
    '"{word}" across ...': '"{word}" across ...',
    '... across "{word}"': '... across "{word}"',
    '"{word}" inside ...': '"{word}" inside ...',
    '... inside "{word}"': '... inside "{word}"',
    '"{word}" without ...': '"{word}" without ...',
    '... without "{word}"': '... without "{word}"',
    '"{word}" around ...': '"{word}" around ...',
    '... around "{word}"': '... around "{word}"',
    '"{word}" toward ...': '"{word}" toward ...',
    '... toward "{word}"': '... toward "{word}"',
    '"{word}" upon ...': '"{word}" upon ...',
    '... upon "{word}"': '... upon "{word}"',
    '"{word}" among ...': '"{word}" among ...',
    '... among "{word}"': '... among "{word}"',
    '"{word}" once ...': '"{word}" once ...',
    '... once "{word}"': '... once "{word}"',
    '"{word}" outside ...': '"{word}" outside ...',
    '... outside "{word}"': '... outside "{word}"',
    '"{word}" up ...': '"{word}" up ...',
    '... up "{word}"': '... up "{word}"',
    '"{word}" so ...': '"{word}" so ...',
    '... so "{word}"': '... so "{word}"',
    '"{word}" behind ...': '"{word}" behind ...',
    '... behind "{word}"': '... behind "{word}"',
    '"{word}" versus ...': '"{word}" versus ...',
    '... versus "{word}"': '... versus "{word}"',
    '"{word}" since ...': '"{word}" since ...',
    '... since "{word}"': '... since "{word}"',
    '"{word}" vs. ...': '"{word}" vs. ...',
    '... vs. "{word}"': '... vs. "{word}"',
    '"{word}" below ...': '"{word}" below ...',
    '... below "{word}"': '... below "{word}"',
    '"{word}" unless ...': '"{word}" unless ...',
    '... unless "{word}"': '... unless "{word}"',
    '"{word}" vis-a-vis ...': '"{word}" vis-a-vis ...',
    '... vis-a-vis "{word}"': '... vis-a-vis "{word}"',
    '"{word}" except ...': '"{word}" except ...',
    '... except "{word}"': '... except "{word}"',
    '"{word}" onto ...': '"{word}" onto ...',
    '... onto "{word}"': '... onto "{word}"',
    '"{word}" beyond ...': '"{word}" beyond ...',
    '... beyond "{word}"': '... beyond "{word}"',
    '"{word}" amongst ...': '"{word}" amongst ...',
    '... amongst "{word}"': '... amongst "{word}"',
    '"{word}" besides ...': '"{word}" besides ...',
    '... besides "{word}"': '... besides "{word}"',
    '"{word}" bar ...': '"{word}" bar ...',
    '... bar "{word}"': '... bar "{word}"',
    '"{word}" though ...': '"{word}" though ...',
    '... though "{word}"': '... though "{word}"',
    '"{word}" cum ...': '"{word}" cum ...',
    '... cum "{word}"': '... cum "{word}"',
    '"{word}" thru ...': '"{word}" thru ...',
    '... thru "{word}"': '... thru "{word}"',
    '"{word}" en ...': '"{word}" en ...',
    '... en "{word}"': '... en "{word}"',
    '"{word}" above ...': '"{word}" above ...',
    '... above "{word}"': '... above "{word}"',
    '"{word}" re ...': '"{word}" re ...',
    '... re "{word}"': '... re "{word}"',
    '"{word}" although ...': '"{word}" although ...',
    '... although "{word}"': '... although "{word}"',
    '"{word}" plus ...': '"{word}" plus ...',
    '... plus "{word}"': '... plus "{word}"',
    '"{word}" sans ...': '"{word}" sans ...',
    '... sans "{word}"': '... sans "{word}"',
    '"{word}" aboard ...': '"{word}" aboard ...',
    '... aboard "{word}"': '... aboard "{word}"',
    '"{word}" save ...': '"{word}" save ...',
    '... save "{word}"': '... save "{word}"',
    '"{word}" atop ...': '"{word}" atop ...',
    '... atop "{word}"': '... atop "{word}"',
    '"{word}" beside ...': '"{word}" beside ...',
    '... beside "{word}"': '... beside "{word}"',
    '"{word}" unlike ...': '"{word}" unlike ...',
    '... unlike "{word}"': '... unlike "{word}"',
    '"{word}" regarding ...': '"{word}" regarding ...',
    '... regarding "{word}"': '... regarding "{word}"',
    '"{word}" vis-à-vis ...': '"{word}" vis-à-vis ...',
    '... vis-à-vis "{word}"': '... vis-à-vis "{word}"',
    '"{word}" opposite ...': '"{word}" opposite ...',
    '... opposite "{word}"': '... opposite "{word}"',
    '"{word}" amid ...': '"{word}" amid ...',
    '... amid "{word}"': '... amid "{word}"',
    '"{word}" whereas ...': '"{word}" whereas ...',
    '... whereas "{word}"': '... whereas "{word}"',
    '"{word}" notwithstanding ...': '"{word}" notwithstanding ...',
    '... notwithstanding "{word}"': '... notwithstanding "{word}"',
    '"{word}" underneath ...': '"{word}" underneath ...',
    '... underneath "{word}"': '... underneath "{word}"',
    '"{word}" circa ...': '"{word}" circa ...',
    '... circa "{word}"': '... circa "{word}"',
    '"{word}" mid ...': '"{word}" mid ...',
    '... mid "{word}"': '... mid "{word}"',
    '"{word}" here ...': '"{word}" here ...',
    '... here "{word}"': '... here "{word}"',
    '"{word}" beneath ...': '"{word}" beneath ...',
    '... beneath "{word}"': '... beneath "{word}"',
    '"{word}" nearest ...': '"{word}" nearest ...',
    '... nearest "{word}"': '... nearest "{word}"',
    '"{word}" till ...': '"{word}" till ...',
    '... till "{word}"': '... till "{word}"',
    '"{word}" amidst ...': '"{word}" amidst ...',
    '... amidst "{word}"': '... amidst "{word}"',
    '"{word}" whilst ...': '"{word}" whilst ...',
    '... whilst "{word}"': '... whilst "{word}"',
    '"{word}" qua ...': '"{word}" qua ...',
    '... qua "{word}"': '... qua "{word}"',
    '"{word}" albeit ...': '"{word}" albeit ...',
    '... albeit "{word}"': '... albeit "{word}"',
    '"{word}" reference ...': '"{word}" reference ...',
    '... reference "{word}"': '... reference "{word}"',
    '"{word}" post ...': '"{word}" post ...',
    '... post "{word}"': '... post "{word}"',
    '"{word}" lest ...': '"{word}" lest ...',
    '... lest "{word}"': '... lest "{word}"',
    '"{word}" south ...': '"{word}" south ...',
    '... south "{word}"': '... south "{word}"',
    '"{word}" unto ...': '"{word}" unto ...',
    '... unto "{word}"': '... unto "{word}"',
    '"{word}" ex ...': '"{word}" ex ...',
    '... ex "{word}"': '... ex "{word}"',
    '"{word}" v. ...': '"{word}" v. ...',
    '... v. "{word}"': '... v. "{word}"',
    '"{word}" astride ...': '"{word}" astride ...',
    '... astride "{word}"': '... astride "{word}"',
    '"{word}" ago ...': '"{word}" ago ...',
    '... ago "{word}"': '... ago "{word}"',
    '"{word}" agin ...': '"{word}" agin ...',
    '... agin "{word}"': '... agin "{word}"',
    '"{word}" minus ...': '"{word}" minus ...',
    '... minus "{word}"': '... minus "{word}"',
    '"{word}" downstream ...': '"{word}" downstream ...',
    '... downstream "{word}"': '... downstream "{word}"',
    '"{word}" directly ...': '"{word}" directly ...',
    '... directly "{word}"': '... directly "{word}"',
    '"{word}" inland ...': '"{word}" inland ...',
    '... inland "{word}"': '... inland "{word}"',
    '"{word}" immediately ...': '"{word}" immediately ...',
    '... immediately "{word}"': '... immediately "{word}"',
    '"{word}" forth ...': '"{word}" forth ...',
    '... forth "{word}"': '... forth "{word}"',
    '"{word}" worth ...': '"{word}" worth ...',
    '... worth "{word}"': '... worth "{word}"',
    '"{word}" such ...': '"{word}" such ...',
    '... such "{word}"': '... such "{word}"',
    '"{word}" senza ...': '"{word}" senza ...',
    '... senza "{word}"': '... senza "{word}"',
    '"{word}" west ...': '"{word}" west ...',
    '... west "{word}"': '... west "{word}"',
    '"{word}" fore ...': '"{word}" fore ...',
    '... fore "{word}"': '... fore "{word}"',
    '"{word}" offshore ...': '"{word}" offshore ...',
    '... offshore "{word}"': '... offshore "{word}"',
    '"{word}" next ...': '"{word}" next ...',
    '... next "{word}"': '... next "{word}"',
    '"{word}" ere ...': '"{word}" ere ...',
    '... ere "{word}"': '... ere "{word}"',
    '"{word}" layabout ...': '"{word}" layabout ...',
    '... layabout "{word}"': '... layabout "{word}"',
    '"{word}" pro ...': '"{word}" pro ...',
    '... pro "{word}"': '... pro "{word}"',
    '"{word}" away ...': '"{word}" away ...',
    '... away "{word}"': '... away "{word}"',
    '"{word}" betwixt ...': '"{word}" betwixt ...',
    '... betwixt "{word}"': '... betwixt "{word}"',
    '"{word}" north ...': '"{word}" north ...',
    '... north "{word}"': '... north "{word}"',
    '"{word}" anent ...': '"{word}" anent ...',
    '... anent "{word}"': '... anent "{word}"',
    '"{word}" respecting ...': '"{word}" respecting ...',
    '... respecting "{word}"': '... respecting "{word}"',
    '"{word}" concerning ...': '"{word}" concerning ...',
    '... concerning "{word}"': '... concerning "{word}"',
    '"{word}" thoughout ...': '"{word}" thoughout ...',
    '... thoughout "{word}"': '... thoughout "{word}"',
    '"{word}" par ...': '"{word}" par ...',
    '... par "{word}"': '... par "{word}"',
    '"{word}" now ...': '"{word}" now ...',
    '... now "{word}"': '... now "{word}"',
    '"{word}" outwith ...': '"{word}" outwith ...',
    '... outwith "{word}"': '... outwith "{word}"',
    '"{word}" frae ...': '"{word}" frae ...',
    '... frae "{word}"': '... frae "{word}"',
    '"{word}" ahead ...': '"{word}" ahead ...',
    '... ahead "{word}"': '... ahead "{word}"',
    '"{word}" underground ...': '"{word}" underground ...',
    '... underground "{word}"': '... underground "{word}"',
    '"{word}" sine ...': '"{word}" sine ...',
    '... sine "{word}"': '... sine "{word}"',
    '"{word}" whereupon ...': '"{word}" whereupon ...',
    '... whereupon "{word}"': '... whereupon "{word}"',
    '"{word}" chez ...': '"{word}" chez ...',
    '... chez "{word}"': '... chez "{word}"',
    '"{word}" less ...': '"{word}" less ...',
    '... less "{word}"': '... less "{word}"',
    '"{word}" aslant ...': '"{word}" aslant ...',
    '... aslant "{word}"': '... aslant "{word}"',
    '"{word}" upstream ...': '"{word}" upstream ...',
    '... upstream "{word}"': '... upstream "{word}"',
    '"{word}" wherever ...': '"{word}" wherever ...',
    '... wherever "{word}"': '... wherever "{word}"',
    '"{word}" considering ...': '"{word}" considering ...',
    '... considering "{word}"': '... considering "{word}"',
    '"{word}" thro ...': '"{word}" thro ...',
    '... thro "{word}"': '... thro "{word}"',
    '"{word}" overhead ...': '"{word}" overhead ...',
    '... overhead "{word}"': '... overhead "{word}"',
    '"{word}" abaft ...': '"{word}" abaft ...',
    '... abaft "{word}"': '... abaft "{word}"',
    '"{word}" nigh ...': '"{word}" nigh ...',
    '... nigh "{word}"': '... nigh "{word}"',
    '"{word}" afore ...': '"{word}" afore ...',
    '... afore "{word}"': '... afore "{word}"',
    '"{word}" withal ...': '"{word}" withal ...',
    '... withal "{word}"': '... withal "{word}"',
    '"{word}" downwind ...': '"{word}" downwind ...',
    '... downwind "{word}"': '... downwind "{word}"',
    '"{word}" where ...': '"{word}" where ...',
    '... where "{word}"': '... where "{word}"',
    '"{word}" whither ...': '"{word}" whither ...',
    '... whither "{word}"': '... whither "{word}"',
    '"{word}" pace ...': '"{word}" pace ...',
    '... pace "{word}"': '... pace "{word}"',
    '"{word}" sith ...': '"{word}" sith ...',
    '... sith "{word}"': '... sith "{word}"',
    '"{word}" inward ...': '"{word}" inward ...',
    '... inward "{word}"': '... inward "{word}"',
    '"{word}" excepting ...': '"{word}" excepting ...',
    '... excepting "{word}"': '... excepting "{word}"',
    '"{word}" saving ...': '"{word}" saving ...',
    '... saving "{word}"': '... saving "{word}"',
    '"{word}" neath ...': '"{word}" neath ...',
    '... neath "{word}"': '... neath "{word}"',
    '"{word}" athwart ...': '"{word}" athwart ...',
    '... athwart "{word}"': '... athwart "{word}"',
    '"{word}" midst ...': '"{word}" midst ...',
    '... midst "{word}"': '... midst "{word}"',
    '"{word}" insofar ...': '"{word}" insofar ...',
    '... insofar "{word}"': '... insofar "{word}"',
    '"{word}" thwart ...': '"{word}" thwart ...',
    '... thwart "{word}"': '... thwart "{word}"',
    '"{word}" syn ...': '"{word}" syn ...',
    '... syn "{word}"': '... syn "{word}"',
    '"{word}" whenever ...': '"{word}" whenever ...',
    '... whenever "{word}"': '... whenever "{word}"',
    '"{word}" home ...': '"{word}" home ...',
    '... home "{word}"': '... home "{word}"',
    '"{word}" wheresoever ...': '"{word}" wheresoever ...',
    '... wheresoever "{word}"': '... wheresoever "{word}"',
    '"{word}" forby ...': '"{word}" forby ...',
    '... forby "{word}"': '... forby "{word}"',
    '"{word}" syne ...': '"{word}" syne ...',
    '... syne "{word}"': '... syne "{word}"',
    '"{word}" uphill ...': '"{word}" uphill ...',
    '... uphill "{word}"': '... uphill "{word}"',
    '"{word}" whensoever ...': '"{word}" whensoever ...',
    '... whensoever "{word}"': '... whensoever "{word}"',
    '"{word}" when ...': '"{word}" when ...',
    '... when "{word}"': '... when "{word}"',
    '"{word}" failing ...': '"{word}" failing ...',
    '... failing "{word}"': '... failing "{word}"',
    '"{word}" whithersoever ...': '"{word}" whithersoever ...',
    '... whithersoever "{word}"': '... whithersoever "{word}"',
    '"{word}" astraddle ...': '"{word}" astraddle ...',
    '... astraddle "{word}"': '... astraddle "{word}"',
    '"{word}" atween ...': '"{word}" atween ...',
    '... atween "{word}"': '... atween "{word}"',
    '"{word}" piped-in ...': '"{word}" piped-in ...',
    '... piped-in "{word}"': '... piped-in "{word}"',
    '"{word}" sobeit ...': '"{word}" sobeit ...',
    '... sobeit "{word}"': '... sobeit "{word}"',
    '"{word}" wanting ...': '"{word}" wanting ...',
    '... wanting "{word}"': '... wanting "{word}"',
    '"{word}" yet ...': '"{word}" yet ...',
    '... yet "{word}"': '... yet "{word}"',
    '"{word}" barring ...': '"{word}" barring ...',
    '... barring "{word}"': '... barring "{word}"',
    '"{word}" come-on ...': '"{word}" come-on ...',
    '... come-on "{word}"': '... come-on "{word}"',
    '"{word}" forbye ...': '"{word}" forbye ...',
    '... forbye "{word}"': '... forbye "{word}"',
    '"{word}" fornenst ...': '"{word}" fornenst ...',
    '... fornenst "{word}"': '... fornenst "{word}"',
    '"{word}" comeon ...': '"{word}" comeon ...',
    '... comeon "{word}"': '... comeon "{word}"',
    '"{word}" maugre ...': '"{word}" maugre ...',
    '... maugre "{word}"': '... maugre "{word}"',
    '"{word}" anear ...': '"{word}" anear ...',
    '... anear "{word}"': '... anear "{word}"',
    '"{word}" whenas ...': '"{word}" whenas ...',
    '... whenas "{word}"': '... whenas "{word}"',
    '"{word}" howbeit ...': '"{word}" howbeit ...',
    '... howbeit "{word}"': '... howbeit "{word}"',
    '"{word}" neither ...': '"{word}" neither ...',
    '... neither "{word}"': '... neither "{word}"',
    '"{word}" nathless ...': '"{word}" nathless ...',
    '... nathless "{word}"': '... nathless "{word}"',
    '"{word}" whencesoever ...': '"{word}" whencesoever ...',
    '... whencesoever "{word}"': '... whencesoever "{word}"'
  }
}
