export default {
  translations: {
    'Enter your {l2} text here. Markdown and HTML also supported.': '在此键入{l2}文本。同时支持 Markdown 和 HTML。',
    'Look for {l2} music lyrics on Google.': '使用搜索引擎查找{l2}歌词。',
    libraryIntro: '在 “阅览室” 页面直接阅读各式{l2}文献。',
    'Enter a search term in {l2}...': '键入{l2}关键词……',
    'Recommended Channels': '推荐频道',
    'Study any YouTube video that has {l2} subtitles.': '学习任何有{l2}字幕的 YouTube 视频。',
    'Courses that take your {l2} to the next level.': '让您的{l2}步入新阶段的语言课程',
    'Contact {l2} Zero to Hero': '联系{l2}英雄',
    'This is where you can enjoy reading a variety of {l2} books with the help of hover dictionary and the ability to save words.': '在这里，你可以借助光标取词词典阅读各种{l2}书籍。点击任何{l2}单词，将其存入生词本，之后可前往“词典 > 生词本”查看。',
    'For the love of {l2} words.': '只因酷爱{l2}词。',
    'Look up {l2} words here...': '输入{l2}单词……',
    'Look up words here...': '在这里查词……',
    English: '英语',
    'Learn varous languages through English:': '通过英语学习其他语言：',
    'Learn English through various languages:': '让全世界学习英语：',
    Dictionary: '词典',
    Resources: '资源',
    'Lookup Phrases': '查短语',
    Reading: '阅读材料',
    'Audio-Visual': '视听资源',
    Settings: '设置',
    'Lookup Words': '查词',
    Saved: '生词本',
    Random: '随机',
    'Images of “{text}” on the Web': '网上关于 “{text}” 的图片',
    'Image search by': '图片搜索提供方',
    'Collocations with “{text}”': '跟 “{text}” 的词语搭配',
    'Sentences with “{text}”': '有 “{text}” 的句子',
    '“{text}” videos on YouTube': '在 YouTube 上关于 “{text}” 的视频',
    'Collocations provided by': '词语搭配提供方',
    'Sentences provided by': '例句提供方',
    'Search for more sentences at': '用其他服务搜索更多例句',
    '"{word}" and/or ...': '"{word}" 的并列搭配',
    'nouns modified by "{word}"': '"{word}" 修饰的名词',
    'objects of "{word}"': '"{word}" 的宾语',
    'subjects of "{word}"': '"{word}" 的主语',
    'prepositional phrases': '介词短语',
    'pronominal objects of "{word}"': '"{word}" 的宾语代词',
    'verbs with "{word}" as object': '以 "{word}" 为宾语的动词',
    'verbs with "{word}" as subject': '以 "{word}" 为主语的动词',
    'adjective predicates of "{word}"': '"{word}" 的形容词谓语',
    '"{word}" is a ...': '"{word}" is a ...',
    '{word}\'s ...': '{word}\'s ...',
    'possessors of "{word}"': '"{word}" 的所属',
    'pronominal possessors of "{word}"': '"{word}" 的所属代词',
    'usage patterns': '使用模式',
    '... is a "{word}"': '... is a "{word}"',
    'verbs with particle "up" and "{word}" as object': '动词 + up {word}',
    'verbs with particle "out" and "{word}" as object': '动词 + out {word}',
    'verbs with particle "down" and "{word}" as object': '动词 + down {word}',
    'verbs with particle "off" and "{word}" as object': '动词 + off {word}',
    'verbs with particle "over" and "{word}" as object': '动词 + over {word}',
    'modifiers of "{word}"': '修饰 "{word}" 的词',
    'infinitive objects of "{word}"': '"{word}" 的不定式宾语',
    'verbs complemented by "{word}"': '以 "{word}" 为补语的动词',
    'verbs before "{word}"': '在 "{word}" 之前的动词',
    'subjects of "be {word}"': '"be {word}" 的主语',
    'verbs with particle "away" and "{word}" as object': '动词 + away {word}',
    'My Words': '生词本',
    'These words are stored in your browser\'s local storage, which persists unless you clear your browsing data.':
      '这些单词将存储于浏览器的本地存储（local storage）中。除非您清除浏览数据，否则该存储会持续保留。',
    'Export CSV': '导出 CSV 文件',
    'Clear': '清除',
    'Inlcude:': '包括：',
    'copyPasteCSV': 
    '将下面的文本<b>复制</b>并<b>粘贴</b>到电子表格程序中，或导入到类似 Anki 或 Quizlet 的背单词程序中。',
    'Pronunciation': '发音',
    'Definitions': '释义',
    'Text Reader': '文本阅读器',
    'Generate': '生成',
    'Less words': '少标些词',
    'More words': '多标些词',
    'Study Sheet Creator': '生词提取器',
    'textReaderIntro': '在一些英文文本中书写或粘贴，带注释的文本将显示在文本框下方。您也可以使用<b>Markdown</b>或<b>HTML</b>标签。所有内容都会自动保存到浏览器的 <code>localstorage</code> 里，因此即使刷新浏览器，输入的所有内容仍会保留在此。',
    'Not sure what to read?': '不知道该读什么吗？',
    'Try these resources:': '试试以下资源',
    'YouTube Transcript': '学习 YouTube 字幕',
    'Library': '阅览室',
    'Custom Reading': '自定义阅读',
    'Read any online document by pasting the URL.': '粘贴网址，阅读任意网上文章。',
    'Study YouTube Subtitles': '学习 YouTube 字幕',
    'Search YouTube': '搜索 YouTube',
    'Go': '前往',
    'Study': '学习',
    'Videos': '视频',
    'Playlists': '播放列表',
    'Note:': '注意：',
    'Videos in playlists may not have subtitles.': '播放列表中的某些视频可能没有字幕。',
    'Text Corpus Settings': '语料库设置',
    'Corpus': '语料库',
    'Code': '代码',
    'Language': '语言',
    'Words': '单词数',
    'Note': '备注',
    'Courses': '课程',
    'Contact': '联系方式',
    'Contact Us': '联系我们',
    'Language Courses': '语言课程',
    'Textbooks': '课本',
    'Video Count': '视频总数',
    'Pricing': '价格',
    'Schedule': '发布计划表',
    'FAQ': '常见问题',
    'Affiliate Program': '申请销售代理',
    'View all of our courses on': '查看所有课程，前往',
    '<b>Teachable</b> is an online platform that hosts video courses.': '<b>Teachable</b> 是一个第三方代管视频课程的在线平台。',
    'Course Textbooks': '课程中使用的课本',
    'Pricing Chart': '价格一览表',    
    'Contact Ken with general or business inquiries.': '一般业务咨询，请联系 Ken。',
    'Ken’s Email:': 'Ken 的邮箱',
    'Ken’s WeChat:': 'Ken 的微信',
    'Contact Jon with course-related questions.': '有关课程内容的问题，请联系 Jon。',
    'If you are taking our courses and have a question regarding any content, leave a comment in the comment area of the lecture.': '如果您正在学习我们的课程，对任何课程内容有疑问，请在视频讲座的评论区留言。',
    'Jon’s Reddit:': 'Jon 的 Reddit',
    'Join our WeChat discussion group': '加入我们的微信聊天群。',
    'Download the WeChat app, scan Ken’s QR code below, leave him a message, and he will invite you into the group.': '下载微信应用，扫描下面 Ken 的二维码，用微信给他发消息，他会邀请你加入群。',
    'Transfer Purchases': '平台兑换码',
    '-ing objects of "{word}"': '"{word}"的 -ing 宾语',
    'adjectives after "{word}"': '"{word}" 后的形容词',
    'adjectives modified by "{word}"': '"{word}"修饰的形容词',
    'adverbs modified by "{word}"': '"{word}"修饰的副词',
    'as reflexive': '反身形式',
    'complements of "{word}"': '"{word}" 的补语',
    'in passive': '被动语态',
    'it\'s "{word}" to ...': 'it\'s "{word}" to ...',
    'objects of "{word} across"': '{word} across ...',
    'objects of "{word} along"': '{word} along ...',
    'objects of "{word} apart"': '{word} apart ...',
    'objects of "{word} around"': '{word} around ...',
    'objects of "{word} aside"': '{word} aside ...',
    'objects of "{word} away"': '{word} away ...',
    'objects of "{word} down"': '{word} down ...',
    'objects of "{word} in"': '{word} in ...',
    'objects of "{word} off"': '{word} off ...',
    'objects of "{word} on"': '{word} on ...',
    'objects of "{word} open"': '{word} open ...',
    'objects of "{word} out"': '{word} out ...',
    'objects of "{word} over"': '{word} over ...',
    'objects of "{word} through"': '{word} through ...',
    'objects of "{word} unto"': '{word} unto ...',
    'objects of "{word} up"': '{word} up ...',
    'objects of "{word} upon"': '{word} upon ...',
    'objects of "{word} whole"': '{word} whole ...',
    'particles after "{word}"': '"{word}" 之后的虚词',
    'particles after "{word}" with object': '"{word}" 之后有宾语的虚词',
    'pronominal subjects of "{word}"': '"{word}"的代词主语',
    'verbs modified by "{word}"': '"{word}" 修饰的动词',
    'verbs with particle "across" and "{word}" as object': '动词 across {word}',
    'verbs with particle "along" and "{word}" as object': '动词 along {word}',
    'verbs with particle "apart" and "{word}" as object': '动词 apart {word}',
    'verbs with particle "around" and "{word}" as object': '动词 around {word}',
    'verbs with particle "aside" and "{word}" as object': '动词 aside {word}',
    'verbs with particle "in" and "{word}" as object': '动词 in {word}',
    'verbs with particle "on" and "{word}" as object': '动词 on {word}',
    'verbs with particle "open" and "{word}" as object': '动词 open {word}',
    'verbs with particle "through" and "{word}" as object': '动词 through {word}',
    'verbs with particle "unto" and "{word}" as object': '动词 unto {word}',
    'verbs with particle "upon" and "{word}" as object': '动词 upon {word}',
    'verbs with particle "whole" and "{word}" as object': '动词 whole {word}',
    'wh-words following "{word}"': '"{word}"后的疑问代词',
    '"{word}" as ...': '"{word}" as ...',
    '... as "{word}"': '... as "{word}"',
    '"{word}" in ...': '"{word}" in ...',
    '... in "{word}"': '... in "{word}"',
    '"{word}" of ...': '"{word}" of ...',
    '... of "{word}"': '... of "{word}"',
    '"{word}" at ...': '"{word}" at ...',
    '... at "{word}"': '... at "{word}"',
    '"{word}" for ...': '"{word}" for ...',
    '... for "{word}"': '... for "{word}"',
    '"{word}" on ...': '"{word}" on ...',
    '... on "{word}"': '... on "{word}"',
    '"{word}" to ...': '"{word}" to ...',
    '... to "{word}"': '... to "{word}"',
    '"{word}" by ...': '"{word}" by ...',
    '... by "{word}"': '... by "{word}"',
    '"{word}" with ...': '"{word}" with ...',
    '... with "{word}"': '... with "{word}"',
    '"{word}" from ...': '"{word}" from ...',
    '... from "{word}"': '... from "{word}"',
    '"{word}" about ...': '"{word}" about ...',
    '... about "{word}"': '... about "{word}"',
    '"{word}" into ...': '"{word}" into ...',
    '... into "{word}"': '... into "{word}"',
    '"{word}" over ...': '"{word}" over ...',
    '... over "{word}"': '... over "{word}"',
    '"{word}" despite ...': '"{word}" despite ...',
    '... despite "{word}"': '... despite "{word}"',
    '"{word}" after ...': '"{word}" after ...',
    '... after "{word}"': '... after "{word}"',
    '"{word}" before ...': '"{word}" before ...',
    '... before "{word}"': '... before "{word}"',
    '"{word}" within ...': '"{word}" within ...',
    '... within "{word}"': '... within "{word}"',
    '"{word}" while ...': '"{word}" while ...',
    '... while "{word}"': '... while "{word}"',
    '"{word}" under ...': '"{word}" under ...',
    '... under "{word}"': '... under "{word}"',
    '"{word}" if ...': '"{word}" if ...',
    '... if "{word}"': '... if "{word}"',
    '"{word}" through ...': '"{word}" through ...',
    '... through "{word}"': '... through "{word}"',
    '"{word}" whether ...': '"{word}" whether ...',
    '... whether "{word}"': '... whether "{word}"',
    '"{word}" via ...': '"{word}" via ...',
    '... via "{word}"': '... via "{word}"',
    '"{word}" past ...': '"{word}" past ...',
    '... past "{word}"': '... past "{word}"',
    '"{word}" during ...': '"{word}" during ...',
    '... during "{word}"': '... during "{word}"',
    '"{word}" like ...': '"{word}" like ...',
    '... like "{word}"': '... like "{word}"',
    '"{word}" against ...': '"{word}" against ...',
    '... against "{word}"': '... against "{word}"',
    '"{word}" towards ...': '"{word}" towards ...',
    '... towards "{word}"': '... towards "{word}"',
    '"{word}" down ...': '"{word}" down ...',
    '... down "{word}"': '... down "{word}"',
    '"{word}" because ...': '"{word}" because ...',
    '... because "{word}"': '... because "{word}"',
    '"{word}" off ...': '"{word}" off ...',
    '... off "{word}"': '... off "{word}"',
    '"{word}" until ...': '"{word}" until ...',
    '... until "{word}"': '... until "{word}"',
    '"{word}" along ...': '"{word}" along ...',
    '... along "{word}"': '... along "{word}"',
    '"{word}" alongside ...': '"{word}" alongside ...',
    '... alongside "{word}"': '... alongside "{word}"',
    '"{word}" out ...': '"{word}" out ...',
    '... out "{word}"': '... out "{word}"',
    '"{word}" than ...': '"{word}" than ...',
    '... than "{word}"': '... than "{word}"',
    '"{word}" near ...': '"{word}" near ...',
    '... near "{word}"': '... near "{word}"',
    '"{word}" throughout ...': '"{word}" throughout ...',
    '... throughout "{word}"': '... throughout "{word}"',
    '"{word}" per ...': '"{word}" per ...',
    '... per "{word}"': '... per "{word}"',
    '"{word}" between ...': '"{word}" between ...',
    '... between "{word}"': '... between "{word}"',
    '"{word}" across ...': '"{word}" across ...',
    '... across "{word}"': '... across "{word}"',
    '"{word}" inside ...': '"{word}" inside ...',
    '... inside "{word}"': '... inside "{word}"',
    '"{word}" without ...': '"{word}" without ...',
    '... without "{word}"': '... without "{word}"',
    '"{word}" around ...': '"{word}" around ...',
    '... around "{word}"': '... around "{word}"',
    '"{word}" toward ...': '"{word}" toward ...',
    '... toward "{word}"': '... toward "{word}"',
    '"{word}" upon ...': '"{word}" upon ...',
    '... upon "{word}"': '... upon "{word}"',
    '"{word}" among ...': '"{word}" among ...',
    '... among "{word}"': '... among "{word}"',
    '"{word}" once ...': '"{word}" once ...',
    '... once "{word}"': '... once "{word}"',
    '"{word}" outside ...': '"{word}" outside ...',
    '... outside "{word}"': '... outside "{word}"',
    '"{word}" up ...': '"{word}" up ...',
    '... up "{word}"': '... up "{word}"',
    '"{word}" so ...': '"{word}" so ...',
    '... so "{word}"': '... so "{word}"',
    '"{word}" behind ...': '"{word}" behind ...',
    '... behind "{word}"': '... behind "{word}"',
    '"{word}" versus ...': '"{word}" versus ...',
    '... versus "{word}"': '... versus "{word}"',
    '"{word}" since ...': '"{word}" since ...',
    '... since "{word}"': '... since "{word}"',
    '"{word}" vs. ...': '"{word}" vs. ...',
    '... vs. "{word}"': '... vs. "{word}"',
    '"{word}" below ...': '"{word}" below ...',
    '... below "{word}"': '... below "{word}"',
    '"{word}" unless ...': '"{word}" unless ...',
    '... unless "{word}"': '... unless "{word}"',
    '"{word}" vis-a-vis ...': '"{word}" vis-a-vis ...',
    '... vis-a-vis "{word}"': '... vis-a-vis "{word}"',
    '"{word}" except ...': '"{word}" except ...',
    '... except "{word}"': '... except "{word}"',
    '"{word}" onto ...': '"{word}" onto ...',
    '... onto "{word}"': '... onto "{word}"',
    '"{word}" beyond ...': '"{word}" beyond ...',
    '... beyond "{word}"': '... beyond "{word}"',
    '"{word}" amongst ...': '"{word}" amongst ...',
    '... amongst "{word}"': '... amongst "{word}"',
    '"{word}" besides ...': '"{word}" besides ...',
    '... besides "{word}"': '... besides "{word}"',
    '"{word}" bar ...': '"{word}" bar ...',
    '... bar "{word}"': '... bar "{word}"',
    '"{word}" though ...': '"{word}" though ...',
    '... though "{word}"': '... though "{word}"',
    '"{word}" cum ...': '"{word}" cum ...',
    '... cum "{word}"': '... cum "{word}"',
    '"{word}" thru ...': '"{word}" thru ...',
    '... thru "{word}"': '... thru "{word}"',
    '"{word}" en ...': '"{word}" en ...',
    '... en "{word}"': '... en "{word}"',
    '"{word}" above ...': '"{word}" above ...',
    '... above "{word}"': '... above "{word}"',
    '"{word}" re ...': '"{word}" re ...',
    '... re "{word}"': '... re "{word}"',
    '"{word}" although ...': '"{word}" although ...',
    '... although "{word}"': '... although "{word}"',
    '"{word}" plus ...': '"{word}" plus ...',
    '... plus "{word}"': '... plus "{word}"',
    '"{word}" sans ...': '"{word}" sans ...',
    '... sans "{word}"': '... sans "{word}"',
    '"{word}" aboard ...': '"{word}" aboard ...',
    '... aboard "{word}"': '... aboard "{word}"',
    '"{word}" save ...': '"{word}" save ...',
    '... save "{word}"': '... save "{word}"',
    '"{word}" atop ...': '"{word}" atop ...',
    '... atop "{word}"': '... atop "{word}"',
    '"{word}" beside ...': '"{word}" beside ...',
    '... beside "{word}"': '... beside "{word}"',
    '"{word}" unlike ...': '"{word}" unlike ...',
    '... unlike "{word}"': '... unlike "{word}"',
    '"{word}" regarding ...': '"{word}" regarding ...',
    '... regarding "{word}"': '... regarding "{word}"',
    '"{word}" vis-à-vis ...': '"{word}" vis-à-vis ...',
    '... vis-à-vis "{word}"': '... vis-à-vis "{word}"',
    '"{word}" opposite ...': '"{word}" opposite ...',
    '... opposite "{word}"': '... opposite "{word}"',
    '"{word}" amid ...': '"{word}" amid ...',
    '... amid "{word}"': '... amid "{word}"',
    '"{word}" whereas ...': '"{word}" whereas ...',
    '... whereas "{word}"': '... whereas "{word}"',
    '"{word}" notwithstanding ...': '"{word}" notwithstanding ...',
    '... notwithstanding "{word}"': '... notwithstanding "{word}"',
    '"{word}" underneath ...': '"{word}" underneath ...',
    '... underneath "{word}"': '... underneath "{word}"',
    '"{word}" circa ...': '"{word}" circa ...',
    '... circa "{word}"': '... circa "{word}"',
    '"{word}" mid ...': '"{word}" mid ...',
    '... mid "{word}"': '... mid "{word}"',
    '"{word}" here ...': '"{word}" here ...',
    '... here "{word}"': '... here "{word}"',
    '"{word}" beneath ...': '"{word}" beneath ...',
    '... beneath "{word}"': '... beneath "{word}"',
    '"{word}" nearest ...': '"{word}" nearest ...',
    '... nearest "{word}"': '... nearest "{word}"',
    '"{word}" till ...': '"{word}" till ...',
    '... till "{word}"': '... till "{word}"',
    '"{word}" amidst ...': '"{word}" amidst ...',
    '... amidst "{word}"': '... amidst "{word}"',
    '"{word}" whilst ...': '"{word}" whilst ...',
    '... whilst "{word}"': '... whilst "{word}"',
    '"{word}" qua ...': '"{word}" qua ...',
    '... qua "{word}"': '... qua "{word}"',
    '"{word}" albeit ...': '"{word}" albeit ...',
    '... albeit "{word}"': '... albeit "{word}"',
    '"{word}" reference ...': '"{word}" reference ...',
    '... reference "{word}"': '... reference "{word}"',
    '"{word}" post ...': '"{word}" post ...',
    '... post "{word}"': '... post "{word}"',
    '"{word}" lest ...': '"{word}" lest ...',
    '... lest "{word}"': '... lest "{word}"',
    '"{word}" south ...': '"{word}" south ...',
    '... south "{word}"': '... south "{word}"',
    '"{word}" unto ...': '"{word}" unto ...',
    '... unto "{word}"': '... unto "{word}"',
    '"{word}" ex ...': '"{word}" ex ...',
    '... ex "{word}"': '... ex "{word}"',
    '"{word}" v. ...': '"{word}" v. ...',
    '... v. "{word}"': '... v. "{word}"',
    '"{word}" astride ...': '"{word}" astride ...',
    '... astride "{word}"': '... astride "{word}"',
    '"{word}" ago ...': '"{word}" ago ...',
    '... ago "{word}"': '... ago "{word}"',
    '"{word}" agin ...': '"{word}" agin ...',
    '... agin "{word}"': '... agin "{word}"',
    '"{word}" minus ...': '"{word}" minus ...',
    '... minus "{word}"': '... minus "{word}"',
    '"{word}" downstream ...': '"{word}" downstream ...',
    '... downstream "{word}"': '... downstream "{word}"',
    '"{word}" directly ...': '"{word}" directly ...',
    '... directly "{word}"': '... directly "{word}"',
    '"{word}" inland ...': '"{word}" inland ...',
    '... inland "{word}"': '... inland "{word}"',
    '"{word}" immediately ...': '"{word}" immediately ...',
    '... immediately "{word}"': '... immediately "{word}"',
    '"{word}" forth ...': '"{word}" forth ...',
    '... forth "{word}"': '... forth "{word}"',
    '"{word}" worth ...': '"{word}" worth ...',
    '... worth "{word}"': '... worth "{word}"',
    '"{word}" such ...': '"{word}" such ...',
    '... such "{word}"': '... such "{word}"',
    '"{word}" senza ...': '"{word}" senza ...',
    '... senza "{word}"': '... senza "{word}"',
    '"{word}" west ...': '"{word}" west ...',
    '... west "{word}"': '... west "{word}"',
    '"{word}" fore ...': '"{word}" fore ...',
    '... fore "{word}"': '... fore "{word}"',
    '"{word}" offshore ...': '"{word}" offshore ...',
    '... offshore "{word}"': '... offshore "{word}"',
    '"{word}" next ...': '"{word}" next ...',
    '... next "{word}"': '... next "{word}"',
    '"{word}" ere ...': '"{word}" ere ...',
    '... ere "{word}"': '... ere "{word}"',
    '"{word}" layabout ...': '"{word}" layabout ...',
    '... layabout "{word}"': '... layabout "{word}"',
    '"{word}" pro ...': '"{word}" pro ...',
    '... pro "{word}"': '... pro "{word}"',
    '"{word}" away ...': '"{word}" away ...',
    '... away "{word}"': '... away "{word}"',
    '"{word}" betwixt ...': '"{word}" betwixt ...',
    '... betwixt "{word}"': '... betwixt "{word}"',
    '"{word}" north ...': '"{word}" north ...',
    '... north "{word}"': '... north "{word}"',
    '"{word}" anent ...': '"{word}" anent ...',
    '... anent "{word}"': '... anent "{word}"',
    '"{word}" respecting ...': '"{word}" respecting ...',
    '... respecting "{word}"': '... respecting "{word}"',
    '"{word}" concerning ...': '"{word}" concerning ...',
    '... concerning "{word}"': '... concerning "{word}"',
    '"{word}" thoughout ...': '"{word}" thoughout ...',
    '... thoughout "{word}"': '... thoughout "{word}"',
    '"{word}" par ...': '"{word}" par ...',
    '... par "{word}"': '... par "{word}"',
    '"{word}" now ...': '"{word}" now ...',
    '... now "{word}"': '... now "{word}"',
    '"{word}" outwith ...': '"{word}" outwith ...',
    '... outwith "{word}"': '... outwith "{word}"',
    '"{word}" frae ...': '"{word}" frae ...',
    '... frae "{word}"': '... frae "{word}"',
    '"{word}" ahead ...': '"{word}" ahead ...',
    '... ahead "{word}"': '... ahead "{word}"',
    '"{word}" underground ...': '"{word}" underground ...',
    '... underground "{word}"': '... underground "{word}"',
    '"{word}" sine ...': '"{word}" sine ...',
    '... sine "{word}"': '... sine "{word}"',
    '"{word}" whereupon ...': '"{word}" whereupon ...',
    '... whereupon "{word}"': '... whereupon "{word}"',
    '"{word}" chez ...': '"{word}" chez ...',
    '... chez "{word}"': '... chez "{word}"',
    '"{word}" less ...': '"{word}" less ...',
    '... less "{word}"': '... less "{word}"',
    '"{word}" aslant ...': '"{word}" aslant ...',
    '... aslant "{word}"': '... aslant "{word}"',
    '"{word}" upstream ...': '"{word}" upstream ...',
    '... upstream "{word}"': '... upstream "{word}"',
    '"{word}" wherever ...': '"{word}" wherever ...',
    '... wherever "{word}"': '... wherever "{word}"',
    '"{word}" considering ...': '"{word}" considering ...',
    '... considering "{word}"': '... considering "{word}"',
    '"{word}" thro ...': '"{word}" thro ...',
    '... thro "{word}"': '... thro "{word}"',
    '"{word}" overhead ...': '"{word}" overhead ...',
    '... overhead "{word}"': '... overhead "{word}"',
    '"{word}" abaft ...': '"{word}" abaft ...',
    '... abaft "{word}"': '... abaft "{word}"',
    '"{word}" nigh ...': '"{word}" nigh ...',
    '... nigh "{word}"': '... nigh "{word}"',
    '"{word}" afore ...': '"{word}" afore ...',
    '... afore "{word}"': '... afore "{word}"',
    '"{word}" withal ...': '"{word}" withal ...',
    '... withal "{word}"': '... withal "{word}"',
    '"{word}" downwind ...': '"{word}" downwind ...',
    '... downwind "{word}"': '... downwind "{word}"',
    '"{word}" where ...': '"{word}" where ...',
    '... where "{word}"': '... where "{word}"',
    '"{word}" whither ...': '"{word}" whither ...',
    '... whither "{word}"': '... whither "{word}"',
    '"{word}" pace ...': '"{word}" pace ...',
    '... pace "{word}"': '... pace "{word}"',
    '"{word}" sith ...': '"{word}" sith ...',
    '... sith "{word}"': '... sith "{word}"',
    '"{word}" inward ...': '"{word}" inward ...',
    '... inward "{word}"': '... inward "{word}"',
    '"{word}" excepting ...': '"{word}" excepting ...',
    '... excepting "{word}"': '... excepting "{word}"',
    '"{word}" saving ...': '"{word}" saving ...',
    '... saving "{word}"': '... saving "{word}"',
    '"{word}" neath ...': '"{word}" neath ...',
    '... neath "{word}"': '... neath "{word}"',
    '"{word}" athwart ...': '"{word}" athwart ...',
    '... athwart "{word}"': '... athwart "{word}"',
    '"{word}" midst ...': '"{word}" midst ...',
    '... midst "{word}"': '... midst "{word}"',
    '"{word}" insofar ...': '"{word}" insofar ...',
    '... insofar "{word}"': '... insofar "{word}"',
    '"{word}" thwart ...': '"{word}" thwart ...',
    '... thwart "{word}"': '... thwart "{word}"',
    '"{word}" syn ...': '"{word}" syn ...',
    '... syn "{word}"': '... syn "{word}"',
    '"{word}" whenever ...': '"{word}" whenever ...',
    '... whenever "{word}"': '... whenever "{word}"',
    '"{word}" home ...': '"{word}" home ...',
    '... home "{word}"': '... home "{word}"',
    '"{word}" wheresoever ...': '"{word}" wheresoever ...',
    '... wheresoever "{word}"': '... wheresoever "{word}"',
    '"{word}" forby ...': '"{word}" forby ...',
    '... forby "{word}"': '... forby "{word}"',
    '"{word}" syne ...': '"{word}" syne ...',
    '... syne "{word}"': '... syne "{word}"',
    '"{word}" uphill ...': '"{word}" uphill ...',
    '... uphill "{word}"': '... uphill "{word}"',
    '"{word}" whensoever ...': '"{word}" whensoever ...',
    '... whensoever "{word}"': '... whensoever "{word}"',
    '"{word}" when ...': '"{word}" when ...',
    '... when "{word}"': '... when "{word}"',
    '"{word}" failing ...': '"{word}" failing ...',
    '... failing "{word}"': '... failing "{word}"',
    '"{word}" whithersoever ...': '"{word}" whithersoever ...',
    '... whithersoever "{word}"': '... whithersoever "{word}"',
    '"{word}" astraddle ...': '"{word}" astraddle ...',
    '... astraddle "{word}"': '... astraddle "{word}"',
    '"{word}" atween ...': '"{word}" atween ...',
    '... atween "{word}"': '... atween "{word}"',
    '"{word}" piped-in ...': '"{word}" piped-in ...',
    '... piped-in "{word}"': '... piped-in "{word}"',
    '"{word}" sobeit ...': '"{word}" sobeit ...',
    '... sobeit "{word}"': '... sobeit "{word}"',
    '"{word}" wanting ...': '"{word}" wanting ...',
    '... wanting "{word}"': '... wanting "{word}"',
    '"{word}" yet ...': '"{word}" yet ...',
    '... yet "{word}"': '... yet "{word}"',
    '"{word}" barring ...': '"{word}" barring ...',
    '... barring "{word}"': '... barring "{word}"',
    '"{word}" come-on ...': '"{word}" come-on ...',
    '... come-on "{word}"': '... come-on "{word}"',
    '"{word}" forbye ...': '"{word}" forbye ...',
    '... forbye "{word}"': '... forbye "{word}"',
    '"{word}" fornenst ...': '"{word}" fornenst ...',
    '... fornenst "{word}"': '... fornenst "{word}"',
    '"{word}" comeon ...': '"{word}" comeon ...',
    '... comeon "{word}"': '... comeon "{word}"',
    '"{word}" maugre ...': '"{word}" maugre ...',
    '... maugre "{word}"': '... maugre "{word}"',
    '"{word}" anear ...': '"{word}" anear ...',
    '... anear "{word}"': '... anear "{word}"',
    '"{word}" whenas ...': '"{word}" whenas ...',
    '... whenas "{word}"': '... whenas "{word}"',
    '"{word}" howbeit ...': '"{word}" howbeit ...',
    '... howbeit "{word}"': '... howbeit "{word}"',
    '"{word}" neither ...': '"{word}" neither ...',
    '... neither "{word}"': '... neither "{word}"',
    '"{word}" nathless ...': '"{word}" nathless ...',
    '... nathless "{word}"': '... nathless "{word}"',
    '"{word}" whencesoever ...': '"{word}" whencesoever ...',
    '... whencesoever "{word}"': '... whencesoever "{word}"',
    'Show {count} More': '显示另外 {count} 项'
  }
}
